name: Generate Podcast Feeds
on : [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repo
       uses: actions/release@v3
     - name: Setup Python
       uses: actions/setup-python@v4
       with:
        python-version: '3.10'
     - name: Install Dependancies
       run:
        python -m pip install --upgrade pip
        pip install pyyaml
     - name: Run Feed Generator
       run: python feed.py
     - name: Push Repo
       run:
        git config user.name CloudKing2023
        git config user.mail josephigwe1990@gmail.com
        git add .
        git commit -m "Modified Feed"
        git push
       
        
